### ISSUE TITLE
UTF-8 characters are not decoded properly

### ISSUE THREAD

**Issue by rbioteau** [de-jcup/asp#23]
It leads to errors when using an eclipse workspace at a location containing such characters (eg: `é`)

The issue comes from the request/response encryption that only support ` ISO-8859-1` charset. To avoid this issue I've made a PR suggesting to escape non ISO-8859-1 characters with their unicodes using Apache commons-text [StringEscapeUtils](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringEscapeUtils.html) `escapeJava` and `unescapeJava` method.

**Comment by de-jcup** [comment]
Thanx for reporting. I will start review of PR soon.
